#!/usr/bin/env bash
# scripts/ops/setup-named-tunnel.sh — ES-wave-6 §D5 AC-D5-1
#
# One-time setup for a named cloudflared tunnel (replaces the per-session
# random *.trycloudflare.com URL drift). Idempotent: if the tunnel + DNS
# already exist, prints status + exits 0.
#
# Usage: bash scripts/ops/setup-named-tunnel.sh [hostname]
#   If hostname omitted, prompts interactively.

set -euo pipefail

TUNNEL_NAME="flowblinq-uat-laptop"
HOSTNAME_ARG="${1:-}"

if ! command -v cloudflared >/dev/null 2>&1; then
  echo "[abort] cloudflared not found in PATH. Install via https://developers.cloudflare.com/cloudflared/" >&2
  exit 2
fi

if [ -z "$HOSTNAME_ARG" ]; then
  read -r -p "Tunnel hostname (e.g. uat.flowblinq.dev): " HOSTNAME_ARG
fi
if [ -z "$HOSTNAME_ARG" ]; then
  echo "[abort] hostname required" >&2
  exit 1
fi

CONFIG_DIR="$HOME/.cloudflared"
CONFIG_FILE="$CONFIG_DIR/${TUNNEL_NAME}.yml"
mkdir -p "$CONFIG_DIR"

# 1. Login (idempotent — no-op if already authenticated).
if [ ! -f "$CONFIG_DIR/cert.pem" ]; then
  echo "[1/4] Cloudflared login (browser will open)..."
  cloudflared tunnel login
else
  echo "[1/4] cloudflared cert.pem already present — skipping login."
fi

# 2. Create the tunnel if missing.
echo "[2/4] Ensuring tunnel '${TUNNEL_NAME}' exists..."
if cloudflared tunnel list 2>/dev/null | awk 'NR>1 {print $2}' | grep -qx "$TUNNEL_NAME"; then
  echo "  already exists."
else
  cloudflared tunnel create "$TUNNEL_NAME"
fi

# 3. Route DNS (idempotent — DNS already routed = exit code printed; safe).
echo "[3/4] Routing DNS ${HOSTNAME_ARG} → ${TUNNEL_NAME}..."
cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME_ARG" || \
  echo "  (DNS likely already routed — continuing)"

# 4. Write the per-tunnel config (overwrite is safe; runtime-only).
TUNNEL_ID=$(cloudflared tunnel list 2>/dev/null | awk -v n="$TUNNEL_NAME" 'NR>1 && $2==n {print $1}' | head -1)
CRED_FILE="$CONFIG_DIR/${TUNNEL_ID}.json"
cat > "$CONFIG_FILE" <<EOF
# Generated by scripts/ops/setup-named-tunnel.sh — do not commit.
tunnel: ${TUNNEL_NAME}
credentials-file: ${CRED_FILE}

ingress:
  - hostname: ${HOSTNAME_ARG}
    service: http://localhost:3000
  - service: http_status:404
EOF

echo "[4/4] Wrote ${CONFIG_FILE}."
echo
echo "Per-session run command:"
echo "  cloudflared tunnel --config ${CONFIG_FILE} run ${TUNNEL_NAME}"
echo
echo "Update .env.docker:"
echo "  QSTASH_CALLBACK_BASE=https://${HOSTNAME_ARG}"
echo "  PIPELINE_CALLBACK_URL=https://${HOSTNAME_ARG}"
echo
echo "Done."
